[package]
name = "network-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
itertools = "0.10.5"
nom = "7.1.3"
sha1 = "0.10.5"
